#!/usr/bin/env python3
"""Generate alloy-mc input files from a single JSON specification.

The specification bundles the chemistry (elements, composition), the lattice
(type + number of coordination shells), the DFT-derived pair interactions
(one symmetric matrix per shell), and the Monte Carlo schedule.  This script
emits the three files the engine reads from its run directory:

    composition.input   target species fractions
    coupling.input      per-neighbor distances, J_ij matrices, offset vectors
    <control>.input     simulation control parameters

and (optionally) a manifest.json recording everything for provenance.

The neighbor geometry is generated from the requested lattice type by
enumerating integer offsets in the *primitive* basis, so the simple-cubic index
grid used by the engine faithfully represents BCC / FCC / SC crystals with
periodic boundary conditions.

Usage:
    python make_inputs.py spec.json --outdir run/
    python make_inputs.py --print-template > spec.json
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

# Primitive lattice vectors (Cartesian, in units of the lattice constant a).
# Integer combinations of these enumerate every site; the resulting Cartesian
# displacements give the true neighbor distances used to define shells.
PRIMITIVE = {
    "sc": [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)],
    "bcc": [(-0.5, 0.5, 0.5), (0.5, -0.5, 0.5), (0.5, 0.5, -0.5)],
    "fcc": [(0.0, 0.5, 0.5), (0.5, 0.0, 0.5), (0.5, 0.5, 0.0)],
}


def generate_shells(lattice: str, n_shells: int, search: int = 4):
    """Return a list of shells; each is (distance, [ (n1,n2,n3), ... ]).

    Distances are in units of the lattice constant.  Shells are the distinct
    neighbor distances in ascending order, excluding the site itself.
    """
    lattice = lattice.lower()
    if lattice not in PRIMITIVE:
        raise ValueError(f"unknown lattice '{lattice}' (use sc, bcc, or fcc)")
    a1, a2, a3 = PRIMITIVE[lattice]

    buckets: dict[float, list[tuple[int, int, int]]] = {}
    for n1 in range(-search, search + 1):
        for n2 in range(-search, search + 1):
            for n3 in range(-search, search + 1):
                if n1 == 0 and n2 == 0 and n3 == 0:
                    continue
                dx = n1 * a1[0] + n2 * a2[0] + n3 * a3[0]
                dy = n1 * a1[1] + n2 * a2[1] + n3 * a3[1]
                dz = n1 * a1[2] + n2 * a2[2] + n3 * a3[2]
                r = math.sqrt(dx * dx + dy * dy + dz * dz)
                key = round(r, 4)
                buckets.setdefault(key, []).append((n1, n2, n3))

    ordered = sorted(buckets.keys())
    if len(ordered) < n_shells:
        raise ValueError(
            f"only {len(ordered)} shells found within search radius {search}; "
            "increase 'search' or reduce n_shells"
        )
    shells = []
    for r in ordered[:n_shells]:
        shells.append((r, sorted(buckets[r])))
    return shells


def validate_matrix(M, ne, shell_idx):
    if len(M) != ne or any(len(row) != ne for row in M):
        raise ValueError(f"shell {shell_idx}: J must be {ne}x{ne}")
    for i in range(ne):
        for j in range(ne):
            if abs(M[i][j] - M[j][i]) > 1e-9:
                raise ValueError(
                    f"shell {shell_idx}: J is not symmetric at ({i},{j})"
                )


def write_coupling(path: Path, shells, couplings, ne):
    """Write coupling.input.

    Each neighbor offset becomes one row:
        r  [J ti tj]*(ne*(ne+1)/2)  n1 n2 n3
    Rows are grouped by ascending shell distance; a terminating row 'r=-1'
    ends the file.
    """
    lines = []
    for s, (r, offsets) in enumerate(shells):
        M = couplings[s]
        # Canonical pair order: (1,1),(1,2),...,(1,ne),(2,2),...,(ne,ne).
        pair_tokens = []
        for i in range(ne):
            for j in range(i, ne):
                pair_tokens.append(f"{M[i][j]:.12g} {i + 1} {j + 1}")
        pair_str = "  ".join(pair_tokens)
        for (n1, n2, n3) in offsets:
            lines.append(f"{r:.3f}  {pair_str}  {n1} {n2} {n3}")
    lines.append("-1")  # terminator
    path.write_text("\n".join(lines) + "\n")


def write_composition(path: Path, comp):
    path.write_text(" ".join(f"{c:.6g}" for c in comp) + "\n")


def write_control(path: Path, spec):
    sim = spec.get("simulation", {})
    elements = spec["elements"]
    lines = [
        "# alloy-mc control file (generated by make_inputs.py)",
        f"elements      {' '.join(elements)}",
        f"lattice       {spec.get('lattice', 'bcc')}",
        f"energy_unit   {spec.get('energy_unit', 'ry')}",
        f"intercept     {spec.get('intercept', 0.0):.12g}",
        f"N             {sim.get('N', 16)}",
        f"T_init        {sim.get('T_init', 100.0)}",
        f"T_final       {sim.get('T_final', 2500.0)}",
        f"n_runs        {sim.get('n_runs', 1)}",
        f"n_drop        {sim.get('n_drop', 1.0e4):g}",
        f"n_samples     {sim.get('n_samples', 5.0e4):g}",
        f"n_separation  {sim.get('n_separation', 1)}",
        f"init_order    {sim.get('init_order', 0)}",
        f"restart       {sim.get('restart', 0)}",
        f"checkpoint_every {sim.get('checkpoint_every', 1000)}",
        f"walltime_hours   {sim.get('walltime_hours', 2.0)}",
    ]
    path.write_text("\n".join(lines) + "\n")


def build(spec: dict, outdir: Path, control_name: str):
    elements = spec["elements"]
    ne = len(elements)
    if ne < 2:
        raise ValueError("need at least 2 elements")

    comp = spec["composition"]
    if len(comp) != ne:
        raise ValueError("composition length must equal number of elements")
    if abs(sum(comp) - 1.0) > 1e-3:
        print(f"warning: composition sums to {sum(comp):.4f} (expected 1.0)",
              file=sys.stderr)

    n_shells = spec.get("n_shells")
    couplings = spec["couplings"]
    if n_shells is None:
        n_shells = len(couplings)
    if len(couplings) != n_shells:
        raise ValueError(
            f"got {len(couplings)} coupling matrices but n_shells={n_shells}"
        )
    for s, M in enumerate(couplings):
        validate_matrix(M, ne, s)

    shells = generate_shells(spec.get("lattice", "bcc"), n_shells,
                             search=spec.get("search", 4))

    outdir.mkdir(parents=True, exist_ok=True)
    write_composition(outdir / "composition.input", comp)
    write_coupling(outdir / "coupling.input", shells, couplings, ne)
    write_control(outdir / control_name, spec)

    manifest = {
        "elements": elements,
        "composition": comp,
        "lattice": spec.get("lattice", "bcc"),
        "n_shells": n_shells,
        "shell_distances": [r for r, _ in shells],
        "shell_neighbor_counts": [len(off) for _, off in shells],
        "energy_unit": spec.get("energy_unit", "ry"),
        "intercept": spec.get("intercept", 0.0),
        "control_file": control_name,
        "simulation": spec.get("simulation", {}),
    }
    (outdir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"Wrote inputs to {outdir}/:")
    print(f"  composition.input  ({ne} elements)")
    print(f"  coupling.input     ({n_shells} shells, "
          f"{sum(len(off) for _, off in shells)} neighbors)")
    print(f"  {control_name}")
    print(f"  manifest.json")
    print("Shell distances (a):", ", ".join(f"{r:.4f}" for r, _ in shells))
    print("Neighbors per shell:", ", ".join(str(len(off)) for _, off in shells))
    return manifest


TEMPLATE = {
    "elements": ["Mo", "Nb", "Ta", "W"],
    "composition": [0.36, 0.22, 0.22, 0.20],
    "lattice": "bcc",
    "n_shells": 2,
    "energy_unit": "ry",
    "intercept": -1.2702430255548436,
    "couplings": [
        [
            [0.0, -0.0104916645, -0.0226029893, -0.0047893703],
            [-0.0104916645, 0.0, -0.0027457974, -0.0036503226],
            [-0.0226029893, -0.0027457974, 0.0, -0.0085071317],
            [-0.0047893703, -0.0036503226, -0.0085071317, 0.0],
        ],
        [
            [0.0, -0.0028205085, -0.0044791364, -0.0012145182],
            [-0.0028205085, 0.0, -0.0005462762, -0.0025356700],
            [-0.0044791364, -0.0005462762, 0.0, -0.0025222868],
            [-0.0012145182, -0.0025356700, -0.0025222868, 0.0],
        ],
    ],
    "simulation": {
        "N": 16,
        "T_init": 100.0,
        "T_final": 2500.0,
        "n_runs": 1,
        "n_drop": 10000,
        "n_samples": 50000,
        "n_separation": 1,
        "init_order": 0,
        "walltime_hours": 2.0,
    },
}


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("spec", nargs="?", help="path to JSON specification")
    p.add_argument("--outdir", default=".", help="output directory (default: .)")
    p.add_argument("--control-name", default="control.input",
                   help="name of the control file to write")
    p.add_argument("--print-template", action="store_true",
                   help="print an example specification to stdout and exit")
    args = p.parse_args()

    if args.print_template:
        json.dump(TEMPLATE, sys.stdout, indent=2)
        sys.stdout.write("\n")
        return

    if not args.spec:
        p.error("a JSON spec is required (or use --print-template)")

    spec = json.loads(Path(args.spec).read_text())
    build(spec, Path(args.outdir), args.control_name)


if __name__ == "__main__":
    main()
